name: Deploy 

on: 
  push:
    branches:    
      - 'main'   
  workflow_dispatch:
env:
  ITCH_USERNAME: vatoz
  ITCH_GAME_ID: i23
  DIR: .
jobs:
  deploy:
    name: Upload to Itch
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        channel:
          - html
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData:  .
          itchUsername: ${{env.ITCH_USERNAME}}
          itchGameId: ${{ env.ITCH_GAME_ID }}
          buildChannel: ${{ matrix.channel }}
          buildNumber: ${{ needs.version.outputs.version_hash }}
